config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
  resource :session, only: %i[new create destroy]
  resources :questions, except: %i[show new index]
  resources :tags, only: [:show]

  get 'show', to: 'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: 'User',
                      optional: true
  has_many :question_tags, dependent: :destroy
  has_many :tags, through: :question_tags, source: :tag
  validates :text,
            presence: true
  validates :text,
            length: { maximum: 255 }

  after_commit :find_tags, on: %i[create update]

  def find_tags
    QuestionTag.where(question: id).destroy_all

    "#{text} #{answer}".downcase.scan(Tag::TAG_REGEXP).uniq.each do |tag_name|
      tags << Tag.where(name: tag_name).first_or_create!
    end
  end
end

app/models/question_tag.rb
class QuestionTag < ApplicationRecord
  belongs_to :question
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  TAG_REGEXP = /#[[:word:]-]+/
  has_many :question_tags, dependent: :destroy
  has_many :questions, through: :question_tags, source: :question

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, format: { with: TAG_REGEXP }
end

app/models/user.rb
require 'openssl'
require 'uri'

class User < ApplicationRecord
  ITERATIONS = 20_000
  DIGEST = OpenSSL::Digest.new('SHA256')
  REGEXP_FOR_USERNAME = /\A\w+\z/
  REGEXP_FOR_COLOR = /\A#\h{3}{1,2}\z/
  MAX_LENGTH = 40

  attr_accessor :password

  has_many :questions, dependent: :destroy

  before_validation :make_downcase
  before_save :encrypt_password
  validates :email, :username,
            presence: true
  validates :email, :username,
            uniqueness: true
  validates :email,
            format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :username,
            length: { maximum: MAX_LENGTH },
            format: { with: REGEXP_FOR_USERNAME }
  validates :password,
            presence: true,
            on: :create
  validates :password,
            confirmation: true
  validates :avatar_url,
            format: { with: URI::DEFAULT_PARSER.make_regexp(%w[http https]) },
            allow_blank: true
  validates :color,
            format: { with: REGEXP_FOR_COLOR }

  def self.authenticate(email, password)
    user = find_by(email: email)

    return unless user.present?

    password_hash = User.hash_to_string(
      OpenSSL::PKCS5.pbkdf2_hmac(password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST)
    )

    return unless user.password_hash == password_hash

    user
  end

  def self.hash_to_string(password_hash)
    password_hash.unpack1('H*')
  end

  private

  def encrypt_password
    if password.present?
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))

      self.password_hash = User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(password, password_salt, ITERATIONS, DIGEST.length, DIGEST)
      )
    end
  end

  def make_downcase
    username&.downcase!
    email&.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def reject_user
    redirect_to root_path, alert: 'Вам сюда низя!'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: %i[edit update destroy]
  before_action :authorize_user, except: [:create]

  def edit; end

  def create
    @question = Question.new(question_create_params)
    @question.author = current_user
    @question.ip = request.remote_ip

    if check_captcha(@question) && @question.save
      redirect_to user_path(@question.user), notice: 'Вопрос задан.'
    else
      render :edit
    end
  end

  def update
    if @question.update(question_update_params)
      redirect_to user_path(@question.user), notice: 'Вопрос сохранен.'
    else
      render :edit
    end
  end

  def destroy
    user = @question.user
    @question.destroy

    redirect_to user_path(user), notice: 'Вопрос удален = (.'
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def authorize_user
    reject_user unless @question.user == current_user
  end

  def question_create_params
    params.require(:question).permit(:user_id, :text)
  end

  def question_update_params
    params.require(:question).permit(:answer)
  end

  def check_captcha(model)
    if current_user.present?
      true
    else
      verify_recaptcha(model: model)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.authenticate(params[:email], params[:password])

    if user.present?
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Вы успешно залогинились'
    else
      flash.now.alert = 'Неправильный email или пароль'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Вы разлогинились! Приходите еще!'
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
    @questions = @tag.questions
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: %i[index create new]

  before_action :authorize_user, except: %i[index new create show]

  def index
    @users = User.all
    @tags = Tag.all
  end

  def new
    redirect_to root_path, alert: 'Вы уже залогинены' if current_user.present?
    @user = User.new
  end

  def create
    redirect_to root_path, alert: 'Вы уже залогинены' if current_user.present?
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: 'Пользователь успешно зарегистрирован!'
      session[:user_id] = @user.id
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Данные обновлены!'
    else
      render 'edit'
    end
  end

  def destroy
    User.destroy(session[:user_id])
    redirect_to root_path, notice: 'Пользователь удален!'
  end

  def show
    @questions = @user.questions.order(created_at: :desc)
    @new_question = @user.questions.build
    @questions_count = @questions.count
    @answers_count = @questions.count(&:answer)
    @unanswered_count = @questions_count - @answers_count
  end

  private

  def authorize_user
    reject_user unless @user == current_user
  end

  def load_user
    @user ||= User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :username, :avatar_url, :color)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      asset_path 'avatar.jpg'
    end
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end

  def load_tags(question)
    Tag.joins(:questions).where('question_tags.question_id = ?', question)
  end
end

app/helpers/author_helper.rb
module AuthorHelper
  def author_info(question)
    if question.author.blank?
      "Анонимус #{question.ip}"
    elsif question.author == current_user
      question.author.username
    else
      link_to question.author.username, user_path(question.author)
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <title>Хорошие вопросы</title>
  <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_pack_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="header">
  <div class="container">
    <div class="header-logo">
      <h1 class="header-title"><%= link_to "Хорошие вопросы", root_path %></h1>
    </div>

    <div class="header-nav">
      <% if current_user %>
        <%= link_to "@#{current_user.username}", user_path(current_user) %> |
        <%= link_to 'Выйти', session_path, data: { method: :delete } %>
      <% else %>
        <%= link_to 'Зарегистрироваться', new_user_path,
                    class: 'button button-light button-small' %>
        <%= link_to 'Войти', new_session_path,
                    class: 'button button-light button-small' %>
      <% end %>
    </div>
  </div>
</div>

<div class="content">
  <div class="container">
    <% if flash.any? %>
      <div class="content-wrapper buffer-both">
        <% flash.each do |name, message| %>
          <%= content_tag :div, message, class: "flash-#{name}" %>
        <% end %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/questions/_form.html.erb
<div class="form">
  <%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
      <div class="form-errors">
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li class="form-error-message"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :user_id %>

    <div class="form-field">
      <%= f.label :text, 'Вопрос', class: 'form-label' %>
      <%= f.text_area :text, class: 'form-textarea' %>
    </div>

    <% if current_user.present? && current_user == @question.user %>
      <div class="form-field">
        <%= f.label :answer, 'Ответ', class: 'form-label' %>
        <%= f.text_area :answer, class: 'form-textarea' %>
      </div>
    <% end %>

    <%= recaptcha_tags unless current_user.present? %>

    <div class="form-action buffer-both">
      <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      или
      <%= link_to "вернуться", user_path(@question.user) %>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<div class="question">
  <div class="question-content">

    <div class="question-text text-lead">
      <%= question.text %>
    </div>

    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= question.answer %>
      </div>
    <% end %>

    <div class="question-date">
      <%= l(question.created_at, format: :short) %>
      <% tags = load_tags(question) %>
      <% tags.each do |tag| %>
        <%= link_to tag.name, tag_path(tag) %>
      <% end %>
    </div>

    <div class="question-author">
      <%= author_info(question) %>
    </div>
  </div>

  <% if question.user == current_user %>

    <% edit_icon = question.answer.blank? ? 'reply' : 'pencil' %>

    <div class="question-actions">
      <%= link_to fa_icon(edit_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question),
                  method: :delete, data: {confirm: 'Точно удалить вопрос?'} %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>

  <div class="column-1-2">
    <%= render 'form' %>
  </div>
</div>

app/views/tags/show.html.erb
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Вопросы с хэштегом <%= @tag.name %></h1>
  </div>
</div>

<div class="user-questions buffer-both">
  <div class="questions-list">
    <% @questions.each do |question| %>
      <%= render partial: 'questions/question', object: question %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Править профиль</h1>

  <div class="column-1-2">
    <%= form_for(@user) do |f| %>

      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label :username, class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :name, class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :avatar_url, class: 'form-label' %>
        <%= f.text_field :avatar_url, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :color, class: 'form-label' %>
        <%= f.color_field :color %>
      </div>

      <div class="buffer-top-large buffer-bottom">
        Если не хотите менять пароль — оставьте эти поля пустыми!
      </div>

      <div class="form-field">
        <%= f.label :password, class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action buffer-top">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      </div>
    <% end %>

    <div class="button-delete">
      <span title="Удалить аккаунт">
      <%= link_to fa_icon('trash'), user_path(@user), method: :delete,
                  data: {confirm: 'Вы точно хотите удалить аккаунт?'},
                  class: 'fa-2x button-trash' %>
      </span>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <% @users.each do |user| %>
    <div class="users-list-item">
      <div class="user-image-div user-image-div-small">
        <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
      </div>
    </div>
  <% end %>

  <div class = "buffer-both">
    <% @tags.each do |tag| %>
      <%= link_to tag.name, tag_path(tag) if tag.questions.any? %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>

  <div class="column-1-2">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>

        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label :email, 'Логин (email)', class: 'form-label' %>
        <%= f.text_field :email, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :username, 'Никнейм', class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :name, 'Имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password, 'Пароль', class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action">
        <%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
      </div>
    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<div class="user-header text-center" style="background-color: <%= @user.color %>">
  <h1 class="title-medium">
    <%= @user.name %>
  </h1>

  <div class="buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div>

  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>

  <h2 class="title-small buffer-both">
    @<%= @user.username %>
  </h2>

  <div class="user-ask-button container text-center">
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>

  <div class="question-statistics container text-center">
    <div class="column-1-3">
      <h2 class="title-small"><%= @questions_count %></h2>
      <p><%= t('.count', count: @questions_count) %></p>
    </div>
    <div class="column-1-3">
      <h2 class="title-small"><%= @answers_count %></h2>
      <p><%= t('.count_answers', count: @answers_count) %></p>
    </div>
    <div class="column-1-3">
      <h2 class="title-small"><%= @unanswered_count %></h2>
      <p><%= t('.count_unanswered', count: @unanswered_count) %></p>
    </div>
  </div>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <div class="form">
      <%= form_for @new_question do |f| %>
        <%= f.hidden_field :user_id %>

        <div class="form-field">
          <%= f.label "Ваш вопрос для @#{@user.username}",
                      class: 'form-label' %>
          <%= f.text_area :text, class: 'form-textarea' %>

        </div>

        <%= recaptcha_tags size: 'compact' unless current_user.present? %>

        <div class="form-action">
          <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
        </div>
        <small class="text-small"> * У Анонимусов будет виден IP</small>
        <% end %>
    </div>
  </div>
</div>

<% if @questions.present? %>
  <div class="column-3-4">
    <div class="user-questions buffer-both">
      <div class="questions-list">
        <% @questions.each do |question| %>
          <%= render partial: 'questions/question', object: question %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>